version: '3.11'

services:
  db:
    image: postgres:15
    container_name: meduzzen-internship-local-db
    env_file:
      - .env.sample
    ports:
      - 5432:5432
  redis:
    image: redis:7
    container_name: meduzzen-internship-local-redis
    ports:
      - 6379:6379
  app:
    build:
      context: .
    container_name: meduzzen-internship-app
    env_file:
      - .env.sample
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis