version: '3.11'

services:
  app:
    build:
      context: .
    container_name: meduzzen-internship-app
    env_file:
      - .env.sample
    ports:
      - "8000:8000"
    #command: ["/internship_fastapi_app/docker/command.sh"]