"""second_commit

Revision ID: df548b3a7ac4
Revises: 8c86128f03eb
Create Date: 2023-10-10 13:52:42.295650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df548b3a7ac4'
down_revision: Union[str, None] = '8c86128f03eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('company_title', sa.String(), nullable=False),
    sa.Column('company_description', sa.String(), nullable=False),
    sa.Column('company_city', sa.String(), nullable=True),
    sa.Column('company_phone', sa.String(), nullable=True),
    sa.Column('company_links', sa.String(), nullable=True),
    sa.Column('company_avatar', sa.String(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Company')
    # ### end Alembic commands ###
